# Numpy 

In [2]:
#importing the module
import numpy as np

In [3]:
#gap between 2 integers in array=>np.arange()=>3rd parameter is gap
#number of integers in array=>np.linspace()=>3rd parameter is number of integers

In [4]:
#simple 1D list
a=[1,2,3,4,5,6]
a

[1, 2, 3, 4, 5, 6]

In [5]:
#converting 1D list to Numpy array
np.array(a)

array([1, 2, 3, 4, 5, 6])

In [6]:
#simple 2D list
b=[[1,2,3],[4,5,6]]
b

[[1, 2, 3], [4, 5, 6]]

In [7]:
#converting 2D list to Numpy array
np.array(b)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#get array of all integers in a range
#1st parameter=>inclusive, 2nd parameter=>exclusive, 3rd parameter(step size)=>gap between 2 integers printed
np.arange(30,40,2)

array([30, 32, 34, 36, 38])

In [9]:
#creating a zeros numpy 1D array 
#parameter=>dimension of array
np.zeros(3)

array([0., 0., 0.])

In [10]:
#creating a zeros numpy 2D array
#parameters=>dimensions of array
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
#creating a ones numpy 1D array
#parameter=>dimension of array
np.ones(3)

array([1., 1., 1.])

In [12]:
#creating a ones numpy 2D array
#parameter=>dimension of array
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
#1st parameter=>starting value, 2nd parameter=>ending value, 3rd parameter(number of equal portions)=>count of numbers printed
#the numbers printed may not be integers
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [14]:
#print an identity matrix
#parameter=>number of rows and columns
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
#generate a random 1D numpy array of numbers between 0 and 1
#parameters=>dimensions of the array
np.random.rand(3)

array([0.79908232, 0.17158585, 0.84089674])

In [16]:
#generate a random 2D numpy array of numbers between 0 and 1
#parameters=>dimensions of the array
np.random.rand(3,2)

array([[0.14790354, 0.07087164],
       [0.31582626, 0.83597407],
       [0.87088784, 0.23072464]])

In [17]:
#generate gaussian/normal distribution values
np.random.randn(3,2)

array([[ 0.74898351,  0.52520282],
       [-1.24459952,  0.99420447],
       [-0.26181071, -0.16477527]])

In [18]:
#generate 1 random integer between a given range
#parameters=>given range
#1st parameter=>inclusive, 2nd parameter=>exclusive
np.random.randint(1,10)

4

In [19]:
#generate a random 1D numpy integer array in a given range
#parameters=>given range
#1st parameter=>inclusive, 2nd parameter=>exclusive, 3rd parameter=>dimension of array
np.random.randint(1,10,4)

array([4, 9, 9, 1])

In [20]:
#generate a random 2D numpy integer array in a given range
#parameters=>given range
#1st parameter=>inclusive, 2nd parameter=>exclusive, 3rd parameter=>dimension of array
np.random.randint(1,10,(3,4))

array([[8, 4, 1, 7],
       [9, 9, 7, 4],
       [9, 4, 7, 9]])

In [21]:
a=np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
#reshaping the array into our favoured dimensions
#parameters=>favoured dimensions (product of dimensions should give the number of elements in actual array)
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
b=np.random.randint(1,20,10)
b

array([14, 11,  4,  1, 19,  7,  8, 19, 17, 13])

In [24]:
#accessing 1 array elements by array indexing
b[5]

7

In [25]:
#accessing few array elements between a given range
#lower limit=>inclusive, upper limit=>exclusive
#:=>everything syntax
b[2:6]

array([ 4,  1, 19,  7])

In [26]:
#finding the maximum value among an array
b.max()

19

In [27]:
#finding the minimum value among an array
b.min()

1

In [28]:
#getting the index position of the maximum value in the array
b.argmax()

4

In [29]:
#getting the index position of the minimum value in the array
b.argmin()

3

In [30]:
#printing the dimensions of any array
c=a.reshape(5,5)
c.shape

(5, 5)

In [31]:
#printing the datatype of elements in array
c.dtype

dtype('int32')

In [32]:
#Index Broadcasting in an array
b[2:5]=0
b

array([14, 11,  0,  0,  0,  7,  8, 19, 17, 13])

In [33]:
#assigning a slice of b to new array c
c=b[5:8]
c

array([ 7,  8, 19])

In [34]:
#we get to see that on chaning elements of c the elements of b are also changed
#here we slice a portion of an array and store it to a new variable
#numpy does not allow to create a new array due to memory issues as numpy always tries to save memory
c[:]=100
b

array([ 14,  11,   0,   0,   0, 100, 100, 100,  17,  13])

In [35]:
#to not affect the original array while we format the new array we need to make a copy of original array
c=b.copy()
c=c[0:2]
c

array([14, 11])

In [36]:
#now we see that the original array is not affected
c[:]=1000
b

array([ 14,  11,   0,   0,   0, 100, 100, 100,  17,  13])

In [37]:
#indexing a 2D Numpy array
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
#accessing elements of 2D array 
d[1,2]

6

In [39]:
d[1][2]

6

In [40]:
e=np.arange(10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
#conditional indexing by which we get boolean outputs
f=e>5
f

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [42]:
e[f]

array([6, 7, 8, 9])

## Numpy Array Operations

In [43]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
#addition of 2 arrays
a+a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
#subtraction of 2 arrays
a-a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
#multiplication of 2 arrays
a*a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [47]:
#addition with scalar
a+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
#subtraction with scalar
a-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [49]:
#multiplication with scalar
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
#since 1st place has a 0/0=nan value so we got error message but still got output
a/a

<ipython-input-50-027fa017d5b2>:2: RuntimeWarning: invalid value encountered in true_divide
  a/a


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [51]:
#since 1st place has a 1/0=infinity value so we got error message but still got output
1/a

<ipython-input-51-4051d61289cc>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/a


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

## Numpy Mathematical Operations

In [52]:
#getting square root values of all digits in array
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [53]:
#getting exponential values of all digits in array
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [54]:
#getting logarithmic values of all digits in array
#since log(0)= -infinity so we got an error message but also received an output
np.log(a)

<ipython-input-54-36cf60da006b>:3: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [59]:
#geting the sin value of each digit in array
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [60]:
#geting the cos value of each digit in array
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [61]:
#geting the tan value of each digit in array
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])